%YAML 1.2
%TAG ! tag:fawkesrobotics.org,cfg/
---
# Configuration meta information document
include:
  # reads files ending in .yaml from conf.d config subdir
  # - !ignore-missing conf.d/
  # Reads the host-specific configuration file, no failure if missing
  - !host-specific host.yaml
---
# Main configuration document

llsfrb:
  log:
    level: info
    general: refbox.log
    clips: clips.log
    game: game.log
    mps_dir: mps

  mps:
    enable: true
    stations:
      C-BS:
        active: true
        type: BS
        host: !ipv4 192.168.2.27
        port: !tcp-port 4840
        connection: mockup
      C-CS1:
        active: true
        host: !ipv4 192.168.2.24
        port: !tcp-port 4840
        type: CS
        connection: mockup
      C-CS2:
        active: true
        host: !ipv4 192.168.2.25
        port: !tcp-port 4840
        type: CS
        connection: mockup
      C-RS1:
        active: true
        host: !ipv4 192.168.2.23
        port: !tcp-port 4840
        type: RS
        connection: mockup
      C-RS2:
        active: true
        host: !ipv4 192.168.2.26
        port: !tcp-port 4840
        type: RS
        connection: mockup
      C-DS:
        active: true
        host: !ipv4 192.168.2.28
        port: !tcp-port 4840
        type: DS
        connection: mockup
      C-SS:
        active: true
        host: !ipv4 192.168.2.22
        port: !tcp-port 4840
        type: SS
        connection: mockup
      M-BS:
        active: true
        host: !ipv4 192.168.2.33
        port: !tcp-port 4840
        type: BS
        connection: mockup
      M-CS1:
        active: true
        host: !ipv4 192.168.2.30
        port: !tcp-port 4840
        type: CS
        connection: mockup
      M-CS2:
        active: true
        host: !ipv4 192.168.2.32
        port: !tcp-port 4840
        type: CS
        connection: mockup
      M-RS1:
        active: true
        host: !ipv4 192.168.2.31
        port: !tcp-port 4840
        type: RS
        connection: mockup
      M-RS2:
        active: true
        host: !ipv4 192.168.2.34
        port: !tcp-port 4840
        type: RS
        connection: mockup
      M-DS:
        active: true
        host: !ipv4 192.168.2.29
        port: !tcp-port 4840
        type: DS
        connection: mockup
      M-SS:
        active: true
        host: !ipv4 192.168.2.35
        port: !tcp-port 4840
        type: SS
        connection: mockup

  clips:
    # Timer interval, in milliseconds
    timer-interval: 40

    main: refbox
    debug: true
    # debug levels: 0 ~ none, 1 ~ minimal, 2 ~ more, 3 ~ maximum
    debug-level: 2
    unwatch-facts: [time, signal, gamestate]
    unwatch-rules: [retract-time,
                    game-update-gametime-points, game-update-last-time,
                    net-send-beacon, net-send-GameState, net-send-OrderInfo,
                    net-send-MachineInfo, net-send-RobotInfo,
                    exploration-send-MachineReportInfo,
                    net-broadcast-MachineInfo, net-send-VersionInfo]

  comm:
    protobuf-dirs: ["@SHAREDIR@/msgs"]

    server-port: !tcp-port 4444

    public-peer:
      # host: !ipv4 192.168.122.255
      host: !ipv4 127.0.0.1
      # port: !udp-port 4444
      send-port: !udp-port 4444
      recv-port: !udp-port 4445

    cyan-peer:
      # host: !ipv4 192.168.122.255
      host: !ipv4 127.0.0.1
      # port: !udp-port 4441
      send-port: !udp-port 4441
      recv-port: !udp-port 4446

    magenta-peer:
      # host: !ipv4 192.168.122.255
      host: !ipv4 127.0.0.1
      # port: !udp-port 4442
      send-port: !udp-port 4442
      recv-port: !udp-port 4447

  mongodb:
    enable: false
    hostport: localhost
    collections:
      text-log: log
      clips-log: clipslog
      protobuf: protobuf

  game:
    teams: [Carologistics]
    crypto-keys:
      Carologistics: randomkey
    # set to true to generate a random field at startup
    random-field: true

  shell:
    refbox-host: localhost
    refbox-port: 4444

  workpiece-tracking:
    enable: false
    fail-safe: true
    broadcast: false

  # A requested delivery in the real world needs to be confirmed 'manually' by
  # the referee before scoring. In simulation this might be tedious and
  # unnecessary. 'Automatic' confirmation grants all delivery requests.
  auto-confirm-delivery: true

  simulation:
    enable: false

    # Disable in case machine feedback from the slides is unavailable (e.g.,
    # if one ring station is unresponsive)
    #
    # Slide counters of ring stations listed here will increment the slide
    # counter whenever a payment is due.
    #
    # This also implicates for all listed machines that:
    #   1. Rings can be mounted without payment and the refbox awards additional
    #      points as if the payment was actually made
    #   2. Points for payments are only given, if they are used afterwards.
    #
    # To register a machine for this behavior, enter its full mane, e.g., to
    # add all ring stations simply use:
    disable-base-payment-check: [C-RS1, C-RS2, M-RS1, M-RS2]
    # disable-base-payment-check: []

    # synchronize refbox time with the time of a simulation
    time-sync:
      enable: true
      # estimate time by using the last given simulation time speed
      # (helps reducing the amount of messages to send)
      estimate-time: true
